package ctester.gui;

import constants.Constants;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.Border;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicSplitPaneDivider;
import javax.swing.plaf.basic.BasicSplitPaneUI;

/**
 *
 * @author dma@logossmartcard.com
 */
public class MainUI extends javax.swing.JFrame 
{    
    /**
     * Creates new form MainUI
     */
    public MainUI() 
    {
        initComponents();        
        setupToolbar();
        setupTestsListLayout();
    }

    /**
     * Sets up the toolbar buttons.
     */
    private void setupToolbar() 
    {
        Image img;
        try 
        {
            img = ImageIO.read(this.getClass().getResource(Constants.RESOURCES_PATH + Constants.NEW_TEST_ICON));
            img = img.getScaledInstance(36, 36, java.awt.Image.SCALE_SMOOTH);
            mAddButton.setIcon(new ImageIcon(img));

            img = ImageIO.read(this.getClass().getResource(Constants.RESOURCES_PATH + Constants.COMPILE_ICON));
            img = img.getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
            mCompileButton.setIcon(new ImageIcon(img));

            img = ImageIO.read(this.getClass().getResource(Constants.RESOURCES_PATH + Constants.RUN_ICON));
            img = img.getScaledInstance(48, 48, java.awt.Image.SCALE_SMOOTH);
            mRunButton.setIcon(new ImageIcon(img));

            img = ImageIO.read(this.getClass().getResource(Constants.RESOURCES_PATH + Constants.SETTINGS_ICON));
            img = img.getScaledInstance(Constants.ICON_WIDTH, Constants.ICON_HEIGHT, java.awt.Image.SCALE_SMOOTH);
            mSettingsButton.setIcon(new ImageIcon(img));

        } catch (IOException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Sets up the container panel to list the tests.
     */
    private void setupTestsListLayout()
    {
        // Make the ScrollPane transparent.
        mTestsScrollPane.setOpaque(false);
        mTestsScrollPane.getViewport().setOpaque(false);
        // Set the correct layout for the tests.
        mTestsListPanel.setLayout(new BoxLayout(mTestsListPanel, BoxLayout.Y_AXIS));
        
        mSplitPane.setUI(new BasicSplitPaneUI() 
        {
            @Override
            public BasicSplitPaneDivider createDefaultDivider() 
            {
                return new BasicSplitPaneDivider(this) 
                {                
                    public void setBorder(Border b) {}

                    @Override
                    public void paint(Graphics g) 
                    {
                        super.paint(g);
                        
                        g.setColor(new Color(51, 51, 51));
                        g.fillRect(0, 0, getSize().width, getSize().height);
                    }
                };
            }
        });
        
        mSplitPane.setBorder(null);
        
        for (int i = 0; i < 13; ++i)
        {
            mTestsListPanel.add(new TestItemUI());            
        }
    }
    
    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mSplitPane = new javax.swing.JSplitPane();
        mRightPanel = new javax.swing.JPanel();
        mLeftPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        mCompileButton = new javax.swing.JButton();
        mAddButton = new javax.swing.JButton();
        mRunButton = new javax.swing.JButton();
        mSettingsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mTestsScrollPane = new javax.swing.JScrollPane();
        mTestsListPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CTester");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Candara Light", 0, 12)); // NOI18N
        setLocation(new java.awt.Point(100, 100));
        setName("mainFrame"); // NOI18N

        mSplitPane.setBorder(null);
        mSplitPane.setDividerLocation(500);
        mSplitPane.setDividerSize(5);
        mSplitPane.setForeground(new java.awt.Color(60, 63, 65));
        mSplitPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mRightPanel.setBackground(new java.awt.Color(58, 58, 79));

        javax.swing.GroupLayout mRightPanelLayout = new javax.swing.GroupLayout(mRightPanel);
        mRightPanel.setLayout(mRightPanelLayout);
        mRightPanelLayout.setHorizontalGroup(
            mRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        mRightPanelLayout.setVerticalGroup(
            mRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        mSplitPane.setRightComponent(mRightPanel);

        mLeftPanel.setBackground(new java.awt.Color(30, 40, 57));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        mCompileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/code-download-white.png"))); // NOI18N
        mCompileButton.setToolTipText("Compile selected tests");
        mCompileButton.setBorderPainted(false);
        mCompileButton.setContentAreaFilled(false);
        mCompileButton.setFocusPainted(false);
        mCompileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/file-add-white.png"))); // NOI18N
        mAddButton.setToolTipText("Add new tests");
        mAddButton.setBorderPainted(false);
        mAddButton.setContentAreaFilled(false);
        mAddButton.setFocusPainted(false);
        mAddButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mRunButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right-white.png"))); // NOI18N
        mRunButton.setToolTipText("Run selected tests");
        mRunButton.setBorderPainted(false);
        mRunButton.setContentAreaFilled(false);
        mRunButton.setFocusPainted(false);
        mRunButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/settings-white.png"))); // NOI18N
        mSettingsButton.setToolTipText("Settings");
        mSettingsButton.setBorderPainted(false);
        mSettingsButton.setContentAreaFilled(false);
        mSettingsButton.setFocusPainted(false);
        mSettingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCompileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mRunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mCompileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mRunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 519, Short.MAX_VALUE)
                .addComponent(mSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(30, 40, 57));
        jPanel2.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Tests");

        mTestsScrollPane.setBorder(null);
        mTestsScrollPane.setOpaque(false);

        mTestsListPanel.setBackground(new java.awt.Color(30, 40, 57));
        mTestsListPanel.setOpaque(false);

        javax.swing.GroupLayout mTestsListPanelLayout = new javax.swing.GroupLayout(mTestsListPanel);
        mTestsListPanel.setLayout(mTestsListPanelLayout);
        mTestsListPanelLayout.setHorizontalGroup(
            mTestsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        mTestsListPanelLayout.setVerticalGroup(
            mTestsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mTestsScrollPane.setViewportView(mTestsListPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(mTestsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(mTestsScrollPane))
        );

        javax.swing.GroupLayout mLeftPanelLayout = new javax.swing.GroupLayout(mLeftPanel);
        mLeftPanel.setLayout(mLeftPanelLayout);
        mLeftPanelLayout.setHorizontalGroup(
            mLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mLeftPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mLeftPanelLayout.setVerticalGroup(
            mLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mSplitPane.setLeftComponent(mLeftPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        try 
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) 
            {
                if ("Darcula".equals(info.getName())) 
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mAddButton;
    private javax.swing.JButton mCompileButton;
    private javax.swing.JPanel mLeftPanel;
    private javax.swing.JPanel mRightPanel;
    private javax.swing.JButton mRunButton;
    private javax.swing.JButton mSettingsButton;
    private javax.swing.JSplitPane mSplitPane;
    private javax.swing.JPanel mTestsListPanel;
    private javax.swing.JScrollPane mTestsScrollPane;
    // End of variables declaration//GEN-END:variables
}
