package ctester.gui;

import constants.Constants;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author dma@logosmartard.com
 */
public class TestItemUI extends javax.swing.JPanel 
{
    /**
     * Creates new form TestItemUI
     */
    public TestItemUI() 
    {
        initComponents();
        setupButtons();
    }
    
    private void setupButtons()
    {
        Image img;
        try 
        {
            img = ImageIO.read(this.getClass().getResource(Constants.RESOURCES_PATH + Constants.RUN_ICON));
            img = img.getScaledInstance(28, 28, java.awt.Image.SCALE_SMOOTH);
            mRunButton.setIcon(new ImageIcon(img));

            img = ImageIO.read(this.getClass().getResource(Constants.RESOURCES_PATH + Constants.REMOVE_TEST_ICON));
            img = img.getScaledInstance(28, 28, java.awt.Image.SCALE_SMOOTH);
            mRemoveButton.setIcon(new ImageIcon(img));

        } catch (IOException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        mRemoveButton = new javax.swing.JButton();
        mRunButton = new javax.swing.JButton();

        setOpaque(false);

        jCheckBox1.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setText("   Test Name");
        jCheckBox1.setContentAreaFilled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        mRemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close-white.png"))); // NOI18N
        mRemoveButton.setToolTipText("Remove test");
        mRemoveButton.setBorderPainted(false);
        mRemoveButton.setContentAreaFilled(false);
        mRemoveButton.setFocusPainted(false);
        mRemoveButton.setPreferredSize(new java.awt.Dimension(4, 4));

        mRunButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right-white.png"))); // NOI18N
        mRunButton.setToolTipText("Run test");
        mRunButton.setBorderPainted(false);
        mRunButton.setContentAreaFilled(false);
        mRunButton.setFocusPainted(false);
        mRunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRunButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(mRunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mRunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void mRunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRunButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mRunButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JButton mRemoveButton;
    private javax.swing.JButton mRunButton;
    // End of variables declaration//GEN-END:variables
}
